return {
    {"ellisonleao/gruvbox.nvim"},
    {"folke/tokyonight.nvim"},
    {"rebelot/kanagawa.nvim"},

    -- Configure LazyVim to load the colorscheme
    {
        "LazyVim/LazyVim",
        opts = {
            colorscheme = "gruvbox",
            lazy = false,
        },
        icons = {
            misc = {
                dots = "󰇘",
            },
            ft = {
                octo = "",
            },
            dap = {
                Stopped             = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
                Breakpoint          = " ",
                BreakpointCondition = " ",
                BreakpointRejected  = { " ", "DiagnosticError" },
                LogPoint            = ".>",
            },
            diagnostics = {
                Error = " ",
                Warn  = " ",
                Hint  = " ",
                Info  = " ",
            },
            git = {
                added    = " ",
                modified = " ",
                removed  = " ",
            },
            kinds = {
                Array         = " ",
                Boolean       = "󰨙 ",
                Class         = " ",
                Codeium       = "󰘦 ",
                Color         = " ",
                Control       = " ",
                Collapsed     = " ",
                Constant      = "󰏿 ",
                Constructor   = " ",
                Copilot       = " ",
                Enum          = " ",
                EnumMember    = " ",
                Event         = " ",
                Field         = " ",
                File          = " ",
                Folder        = " ",
                Function      = "󰊕 ",
                Interface     = " ",
                Key           = " ",
                Keyword       = " ",
                Method        = "󰊕 ",
                Module        = " ",
                Namespace     = "󰦮 ",
                Null          = " ",
                Number        = "󰎠 ",
                Object        = " ",
                Operator      = " ",
                Package       = " ",
                Property      = " ",
                Reference     = " ",
                Snippet       = " ",
                String        = " ",
                Struct        = "󰆼 ",
                TabNine       = "󰏚 ",
                Text          = " ",
                TypeParameter = " ",
                Unit          = " ",
                Value         = " ",
                Variable      = "󰀫 ",
            },
        },
    }
}
